// <auto-generated />
using System;
using HomeHealth.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HomeHealth.Migrations
{
    [DbContext(typeof(HomeHealthDbContext))]
    [Migration("20200407232403_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("HomeHealth.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Dob")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("TEXT")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("TEXT")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("HomeHealth.data.tables.Appointments", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("appointment_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AddressString")
                        .IsRequired()
                        .HasColumnName("Prof_Address1")
                        .HasColumnType("TEXT")
                        .IsFixedLength(true)
                        .HasMaxLength(80)
                        .IsUnicode(false);

                    b.Property<DateTime?>("AppDate")
                        .IsRequired()
                        .HasColumnName("app_date")
                        .HasColumnType("date");

                    b.Property<string>("AppReason")
                        .IsRequired()
                        .HasColumnName("app_reason")
                        .HasColumnType("TEXT")
                        .IsUnicode(false);

                    b.Property<DateTime?>("AppTime")
                        .IsRequired()
                        .HasColumnName("app_time")
                        .HasColumnType("datetime");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasColumnName("patient_id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfessionalId")
                        .IsRequired()
                        .HasColumnName("doctor_id")
                        .HasColumnType("TEXT");

                    b.Property<int>("ishomevisit")
                        .HasColumnName("isHomeVisist")
                        .HasColumnType("INTEGER");

                    b.Property<double>("lat")
                        .HasColumnName("lat")
                        .HasColumnType("REAL");

                    b.Property<double>("lng")
                        .HasColumnName("lng")
                        .HasColumnType("REAL");

                    b.Property<float>("totalcost")
                        .HasColumnName("Total_cost")
                        .HasColumnType("REAL");

                    b.HasKey("AppointmentId");

                    b.HasIndex("PatientId");

                    b.HasIndex("ProfessionalId");

                    b.ToTable("appointment");
                });

            modelBuilder.Entity("HomeHealth.data.tables.Charges", b =>
                {
                    b.Property<int>("ChargeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AppointmentId")
                        .IsRequired()
                        .HasColumnName("appointment_id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Prof_serviceId")
                        .IsRequired()
                        .HasColumnName("service_id")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("serviceCost")
                        .IsRequired()
                        .HasColumnName("Service_Cost")
                        .HasColumnType("REAL");

                    b.HasKey("ChargeId");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("Prof_serviceId");

                    b.HasIndex("ServiceId");

                    b.ToTable("bill");
                });

            modelBuilder.Entity("HomeHealth.data.tables.Comments", b =>
                {
                    b.Property<int>("CommentsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProfessionalId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SenderId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("TEXT");

                    b.HasKey("CommentsId");

                    b.HasIndex("ProfessionalId");

                    b.HasIndex("SenderId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("HomeHealth.data.tables.Messages", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("message_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .HasColumnName("Content")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProfessionalsId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReceiverId")
                        .HasColumnName("ReceiverId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SenderId")
                        .HasColumnName("SenderId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnName("TimeStamp")
                        .HasColumnType("TEXT");

                    b.HasKey("MessageId")
                        .HasName("message_id");

                    b.HasIndex("ProfessionalsId");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("message");
                });

            modelBuilder.Entity("HomeHealth.data.tables.Professional_Service", b =>
                {
                    b.Property<int>("Professional_ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProfessionalId")
                        .HasColumnName("ProfessionalId")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("ServiceCost")
                        .HasColumnName("Service_cost")
                        .HasColumnType("REAL");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Professional_ServiceId")
                        .HasName("Prof_service_id");

                    b.HasIndex("ProfessionalId");

                    b.HasIndex("ServiceId");

                    b.ToTable("Professional_Service");
                });

            modelBuilder.Entity("HomeHealth.data.tables.Professionals", b =>
                {
                    b.Property<int>("ProfessionalsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AddressString")
                        .IsRequired()
                        .HasColumnName("Prof_Address1")
                        .HasColumnType("TEXT")
                        .IsFixedLength(true)
                        .HasMaxLength(80)
                        .IsUnicode(false);

                    b.Property<string>("Biography")
                        .IsRequired()
                        .HasColumnName("Biography")
                        .HasColumnType("TEXT")
                        .HasMaxLength(500);

                    b.Property<int?>("ServiceId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("lat")
                        .HasColumnName("lat")
                        .HasColumnType("REAL");

                    b.Property<double>("lng")
                        .HasColumnName("lng")
                        .HasColumnType("REAL");

                    b.Property<string>("userId")
                        .IsRequired()
                        .HasColumnName("user_id")
                        .HasColumnType("TEXT");

                    b.HasKey("ProfessionalsId")
                        .HasName("pk_Duser_id");

                    b.HasIndex("ServiceId");

                    b.HasIndex("userId")
                        .IsUnique();

                    b.ToTable("ProfessionalsId");
                });

            modelBuilder.Entity("HomeHealth.data.tables.Service", b =>
                {
                    b.Property<int>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnName("Service_name")
                        .HasColumnType("TEXT");

                    b.HasKey("ServiceId");

                    b.ToTable("Service");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("TEXT")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("HomeHealth.data.tables.Appointments", b =>
                {
                    b.HasOne("HomeHealth.Identity.ApplicationUser", "Patient")
                        .WithMany("AppointmentsPati")
                        .HasForeignKey("PatientId")
                        .HasConstraintName("fk_User_patient_id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HomeHealth.Identity.ApplicationUser", "Professional")
                        .WithMany("Appointmentsprof")
                        .HasForeignKey("ProfessionalId")
                        .HasConstraintName("fk_User_Profesional_id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("HomeHealth.data.tables.Charges", b =>
                {
                    b.HasOne("HomeHealth.data.tables.Appointments", "Appointment")
                        .WithMany("Charges")
                        .HasForeignKey("AppointmentId")
                        .HasConstraintName("fk_appointment_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HomeHealth.data.tables.Professional_Service", "Professional_Service")
                        .WithMany("Charges")
                        .HasForeignKey("Prof_serviceId")
                        .HasConstraintName("fk_Charges_prof_service_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HomeHealth.data.tables.Service", null)
                        .WithMany("Charges")
                        .HasForeignKey("ServiceId");
                });

            modelBuilder.Entity("HomeHealth.data.tables.Comments", b =>
                {
                    b.HasOne("HomeHealth.data.tables.Professionals", "Professional")
                        .WithMany("ProfComments")
                        .HasForeignKey("ProfessionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HomeHealth.Identity.ApplicationUser", "Sender")
                        .WithMany("UsersComments")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HomeHealth.data.tables.Messages", b =>
                {
                    b.HasOne("HomeHealth.data.tables.Professionals", null)
                        .WithMany("Messages")
                        .HasForeignKey("ProfessionalsId");

                    b.HasOne("HomeHealth.Identity.ApplicationUser", "Reciever")
                        .WithMany("MessagesRec")
                        .HasForeignKey("ReceiverId")
                        .HasConstraintName("fk_messages_recieverUser");

                    b.HasOne("HomeHealth.Identity.ApplicationUser", "Sender")
                        .WithMany("MessagesSent")
                        .HasForeignKey("SenderId")
                        .HasConstraintName("fk_Messages_SenderUser");
                });

            modelBuilder.Entity("HomeHealth.data.tables.Professional_Service", b =>
                {
                    b.HasOne("HomeHealth.data.tables.Professionals", "Professional")
                        .WithMany("Prof_services")
                        .HasForeignKey("ProfessionalId")
                        .HasConstraintName("k_prof_service_Professional");

                    b.HasOne("HomeHealth.data.tables.Service", "Service")
                        .WithMany("prof_services")
                        .HasForeignKey("ServiceId")
                        .HasConstraintName("fk_prof_service__service");
                });

            modelBuilder.Entity("HomeHealth.data.tables.Professionals", b =>
                {
                    b.HasOne("HomeHealth.data.tables.Service", null)
                        .WithMany("Professionals")
                        .HasForeignKey("ServiceId");

                    b.HasOne("HomeHealth.Identity.ApplicationUser", "user")
                        .WithOne("Professional")
                        .HasForeignKey("HomeHealth.data.tables.Professionals", "userId")
                        .HasConstraintName("fk_Prof_User")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("HomeHealth.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("HomeHealth.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HomeHealth.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("HomeHealth.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
